# frozen_string_literal: true

@mi1 = MenuItem.new(
  english: 'Accounts',
  persian: 'حساب ها',
  arabic: 'الحسابات',
  spanish: 'Cuentas',
  french: 'Comptes',
  turkish: 'Hesaplar',
  portugess: 'Contas',
  dutch: 'Rekeningen',
  russian: 'Счета',
  italian: 'Conti',
  hindi: 'लेखा',
  urdu: 'اکاؤنٹس',
  chiness: '帐户',
  japaness: 'アカウント',
  korean: '계정',
  thai: 'บัญชี',
  malay: 'Akaun',
  indonesian: 'Akun'
).save

mi2 = MenuItem.new(
  english: 'َChart of Accounts',
  persian: 'نمودار حساب ها',
  arabic: 'رسم بياني للحسابات',
  spanish: 'Tabla de cuentas',
  french: 'Tableau des comptes',
  turkish: 'Hesap Planı',
  portugess: 'Tabela de contas',
  dutch: 'Rekeningoverzicht',
  russian: 'Сводный счет',
  italian: 'Tabella dei conti',
  hindi: 'लेखा चार्ट',
  urdu: 'اکاؤنٹس کا چارٹ',
  chiness: '帐户图表',
  japaness: 'アカウントチャート',
  korean: '계정 차트',
  thai: 'แผนภูมิบัญชี',
  malay: 'Akaun Carta',
  indonesian: 'Tabel Akun',
  component: '<ChartOfAccounts />',
  parent_id: @mi1
).save

@mi3 = MenuItem.new(
  english: 'Entity Management',
  persian: 'مدیریت موجودیت',
  arabic: 'إدارة الكيان',
  spanish: 'Gestión de entidades',
  french: 'Gestion des entités',
  turkish: 'Varlık Yönetimi',
  portugess: 'Gerenciamento de entidades',
  dutch: 'Entiteitenbeheer',
  russian: 'Управление сущностями',
  italian: 'Gestione delle entità',
  hindi: 'एंटिटी प्रबंधन',
  urdu: 'اینٹٹی مینجمنٹ',
  chiness: '实体管理',
  japaness: 'エンティティ管理',
  korean: '엔티티 관리',
  thai: 'การจัดการเอนทิตี้',
  malay: 'Pengurusan Eniti',
  indonesian: 'Manajemen Entitas'
).save

@mi4 = MenuItem.new(
  english: 'Entity Types',
  persian: 'انواع موجودیت',
  arabic: 'أنواع الكيان',
  spanish: 'Tipos de entidades',
  french: 'Types d\'entités',
  turkish: 'Varlık Türleri',
  portugess: 'Tipos de entidades',
  dutch: 'Entiteitstypen',
  russian: 'Типы сущностей',
  italian: 'Tipi di entità',
  hindi: 'एंटिटी प्रकार',
  urdu: 'اینٹٹی کیاں',
  chiness: '实体类型',
  japaness: 'エンティティタイプ',
  korean: '엔티티 유형',
  thai: 'ประเภทเอนทิตี้',
  malay: 'Jenis Eniti',
  indonesian: 'Jenis Entitas',
  component: '<EntityTypes />',
  parent_id: @mi3
).save

@mi5 = MenuItem.new(
  english: 'People',
  persian: 'افراد',
  arabic: 'الناس',
  spanish: 'Gente',
  french: 'Gens',
  turkish: 'İnsanlar',
  portugess: 'Pessoas',
  dutch: 'Mensen',
  russian: 'Люди',
  italian: 'Persone',
  hindi: 'लोग',
  urdu: 'لوگ',
  chiness: '人',
  japaness: '人々',
  korean: '사람들',
  thai: 'คน',
  malay: 'Orang',
  indonesian: 'Orang',
  component: '<Entity entityType="1"/>',
  parent_id: @mi3
).save

@mi6 = MenuItem.new(
  english: 'Organizations',
  persian: 'سازمان ها',
  arabic: 'المنظمات',
  spanish: 'Organizaciones',
  french: 'Organisations',
  turkish: 'Kuruluşlar',
  portugess: 'Organizações',
  dutch: 'Organisaties',
  russian: 'Организации',
  italian: 'Organizzazioni',
  hindi: 'संगठन',
  urdu: 'سازمان',
  chiness: '组织',
  japaness: '組織',
  korean: '조직',
  thai: 'องค์กร',
  malay: 'Organisasi',
  indonesian: 'Organisasi',
  component: '<Entity entityType="2"/>',
  parent_id: @mi3
).save
